# Generated by Django 5.0.3 on 2024-04-01 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('s_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[7-9]{1}+[0-9]{9}')])),
                ('rooms', models.IntegerField()),
                ('ac', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
            ],
        ),
    ]
